### ISSUE TITLE
Same path, difference HTTP method confusion

### ISSUE THREAD

**Issue by bensgilbert** [Kronifer/cosmo#15]
https://github.com/Kronifer/cosmo/blob/47ea7f4a91886d8d67388c7caf436e48ba3c2d8a/cosmo/app.py#L60
The paths dictionary uses the route's path as a key. If two routes have the same path, then one will overwrite the other.
https://github.com/Kronifer/cosmo/blob/47ea7f4a91886d8d67388c7caf436e48ba3c2d8a/cosmo/app.py#L118
https://github.com/Kronifer/cosmo/blob/47ea7f4a91886d8d67388c7caf436e48ba3c2d8a/cosmo/app.py#L127
This excludes the overwritten route from being accessed.

**Comment by Kronifer** [comment]
I won't fix this until I find a way to do it that isn't slow as shit
